# nexus-engine/Earthfile
VERSION 0.8

build:
    FROM node:20
    WORKDIR /app
    COPY . .
    RUN npm install -g pnpm@9.6.0
    RUN pnpm install --frozen-lockfile
    RUN pnpm turbo run build --filter=nexus-engine...
    RUN pnpm --filter=nexus-engine deploy /deploy
    SAVE ARTIFACT /deploy AS LOCAL nexus-engine-files

image:
    FROM node:20-slim
    WORKDIR /app
    ENV NODE_ENV=production
    COPY +build/nexus-engine-files .
    CMD ["node", "dist/main.js"]
    SAVE IMAGE nexus-verse/nexus-engine:latest